# Generated by Django 6.1.1 on 2026-09-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_doador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='base',
            field=models.CharField(default='Brasília', max_length=100),
            preserve_default=False,
        ),
    ]
