# Generated by Django 6.1.1 on 2026-09-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_agendamento_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
