# Generated by Django 6.1.1 on 2026-09-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_codigorecuperacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doador',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='doador',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
