# Generated by Django 6.1.1 on 2026-09-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_doador_cidade_doador_cpf_doador_estado_doador_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta', '🚨 Alerta'), ('lembrete', '📅 Lembrete'), ('campanha', '🩸 Campanha'), ('confirmado', '✅ Confirmação'), ('nivel', '🏆 Nível')], default='alerta', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='membros.doador')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
