# Generated by Django 6.1.1 on 2026-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0007_hemocentro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', '⏳ Agendado'), ('realizado', '✅ Realizado'), ('cancelado', '❌ Cancelado'), ('faltou', '⚠️ Faltou')], default='agendado', max_length=20),
        ),
    ]
