# Generated by Django 6.1.1 on 2026-09-21 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0008_agendamento_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('hospital', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('urgencia', models.CharField(choices=[('baixa', '🟢 Baixa'), ('media', '🟡 Média'), ('alta', '🔴 Alta')], default='media', max_length=20)),
                ('descricao', models.TextField()),
                ('contato', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-urgencia', '-criado_em'],
            },
        ),
    ]
