# Generated by Django 6.1.1 on 2026-09-22 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0009_receptor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptor',
            name='status',
            field=models.CharField(choices=[('pendente', '⏳ Pendente'), ('aprovado', '✅ Aprovado'), ('atendido', '🎉 Atendido'), ('expirado', '📅 Expirado'), ('recusado', '❌ Recusado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='receptor',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to=settings.AUTH_USER_MODEL),
        ),
    ]
