# Generated by Django 6.1.1 on 2026-09-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0010_receptor_expira_em_receptor_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='idade_paciente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade do paciente'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='sexo_paciente',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, verbose_name='Sexo do paciente'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='tipo_doacao',
            field=models.CharField(choices=[('sangue', '🩸 Sangue Total'), ('plaquetas', '🟡 Plaquetas'), ('plasma', '🟠 Plasma'), ('medula', '🦴 Medula Óssea'), ('hemacias', '🔴 Concentrado de Hemácias')], default='sangue', max_length=20, verbose_name='Tipo de doação necessária'),
        ),
    ]
