# Generated by Django 6.1.1 on 2026-09-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0011_receptor_idade_paciente_receptor_sexo_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='celular_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular do responsável'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do responsável'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='laudo',
            field=models.FileField(blank=True, help_text='Anexe o laudo médico ou documento que comprove o caso', null=True, upload_to='laudos/', verbose_name='Laudo médico'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='contato',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
