# Generated by Django 6.1.1 on 2026-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0012_receptor_celular_contato_receptor_email_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='🩸', max_length=10, verbose_name='Emoji')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('ativa', '✅ Ativa'), ('breve', '📅 Em breve'), ('urgente', '🚨 Urgente'), ('encerrada', '❌ Encerrada')], default='ativa', max_length=20, verbose_name='Status')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('data', models.CharField(blank=True, max_length=100, verbose_name='Data / Período')),
                ('ativa', models.BooleanField(default=True, verbose_name='Visível no site')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-criada_em'],
            },
        ),
    ]
