# Generated by Django 6.1.1 on 2026-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0013_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='nome_responsavel',
            field=models.CharField(blank=True, help_text='Nome de quem está cuidando do paciente', max_length=200, verbose_name='Nome do responsável'),
        ),
    ]
