# Generated by Django 6.1.1 on 2026-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0014_receptor_nome_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoParceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Hemocentro')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail institucional')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pendente', '⏳ Pendente'), ('aprovado', '✅ Aprovado'), ('recusado', '❌ Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Pedido de Parceria',
                'verbose_name_plural': 'Pedidos de Parceria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
